const candidateList = [
  {Candidate_ID : 1,Party_ID: 1,Candidate_Name:'ဒေါ်အောင်ဆန်းစုကြည်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1940/8/8',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကလန(နိုင်)၁၆၄၁၈၉',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ရန်ကုန်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 2,Party_ID: 6,Candidate_Name:'ဦးသိန်းစိန်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကဘလ(နိုင်)၁၉၇၇၆၅',Education: 'M.C.Sc',Occupation: 'Lecturer',Permanent_Address: 'ပုဂံ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 3,Party_ID: 3,Candidate_Name:'ဦးကြည်အုံး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1985/8/9',Race: 'ရခိုင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/မရန(နိုင်)၁၉၇၇၆၇',Education: 'M.B.B.S',Occupation: 'Doctor',Permanent_Address: 'မုံရွာ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 4,Party_ID: 9,Candidate_Name:'ဦးခင်မောင်ရွှေ',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1976/8/8',Race: 'ပအို့',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/မလန(နိုင်)၁၂၆၁၀၁',Education: 'L.B.B.S',Occupation: 'Lawer',Permanent_Address: 'စစ်ကိုင်း',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 5,Party_ID: 2,Candidate_Name:'ဦးညွန့်ဝင်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/မရန(နိုင်)၁၂၃၄၄၇',Education: 'B.A',Occupation: 'Teacher',Permanent_Address: 'ရွှေဘို',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 6,Party_ID: 7,Candidate_Name:'ဦးအောင်မြင့်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'မွန်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/စကန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'မန္တလေး',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 7,Party_ID: 5,Candidate_Name:'ဦးအောင်ဌေး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1986/8/8',Race: 'ရှမ်း',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/ရဘန(နိုင်)၂၃၁၈၉၀',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'နေပြည်တော်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 8,Party_ID: 8,Candidate_Name:'ဦးဇော်ဇော်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1987/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ယမပ(နိုင်)၁၂၅၄၆၈',Education: 'M.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ပြင်ဦးလွင်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 9,Party_ID: 4,Candidate_Name:'ဒေါ်ထက်ထက်ထွန်း',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'ကချင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/တမန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Developer',Permanent_Address: 'မြိတ်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 10,Party_ID: 10,Candidate_Name:'ဦးဖြိုးမင်းသိန်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1988/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/ပလဘ(နိုင်)၀၉၈၇၄၅',Education: 'M.C.Sc',Occupation: 'Marking Manager',Permanent_Address: 'ပြည်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 11,Party_ID: 1,Candidate_Name:'ဒေါ်အောင်ဆန်းစုကြည်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1940/8/8',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကလန(နိုင်)၁၆၄၁၈၉',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ရန်ကုန်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 12,Party_ID: 6,Candidate_Name:'ဦးသိန်းစိန်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကဘလ(နိုင်)၁၉၇၇၆၅',Education: 'M.C.Sc',Occupation: 'Lecturer',Permanent_Address: 'ပုဂံ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 13,Party_ID: 3,Candidate_Name:'ဦးကြည်အုံး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1985/8/9',Race: 'ရခိုင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/မရန(နိုင်)၁၉၇၇၆၇',Education: 'M.B.B.S',Occupation: 'Doctor',Permanent_Address: 'မုံရွာ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 14,Party_ID: 9,Candidate_Name:'ဦးခင်မောင်ရွှေ',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1976/8/8',Race: 'ပအို့',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/မလန(နိုင်)၁၂၆၁၀၁',Education: 'L.B.B.S',Occupation: 'Lawer',Permanent_Address: 'စစ်ကိုင်း',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 15,Party_ID: 2,Candidate_Name:'ဦးညွန့်ဝင်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/မရန(နိုင်)၁၂၃၄၄၇',Education: 'B.A',Occupation: 'Teacher',Permanent_Address: 'ရွှေဘို',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 16,Party_ID: 7,Candidate_Name:'ဦးအောင်မြင့်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'မွန်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/စကန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'မန္တလေး',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 17,Party_ID: 5,Candidate_Name:'ဦးအောင်ဌေး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1986/8/8',Race: 'ရှမ်း',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/ရဘန(နိုင်)၂၃၁၈၉၀',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'နေပြည်တော်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 18,Party_ID: 8,Candidate_Name:'ဦးဇော်ဇော်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1987/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ယမပ(နိုင်)၁၂၅၄၆၈',Education: 'M.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ပြင်ဦးလွင်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 19,Party_ID: 4,Candidate_Name:'ဒေါ်ထက်ထက်ထွန်း',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'ကချင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/တမန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Developer',Permanent_Address: 'မြိတ်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 20,Party_ID: 10,Candidate_Name:'ဦးဖြိုးမင်းသိန်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1988/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/ပလဘ(နိုင်)၀၉၈၇၄၅',Education: 'M.C.Sc',Occupation: 'Marking Manager',Permanent_Address: 'ပြည်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 21,Party_ID: 1,Candidate_Name:'ဒေါ်အောင်ဆန်းစုကြည်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1940/8/8',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကလန(နိုင်)၁၆၄၁၈၉',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ရန်ကုန်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 22,Party_ID: 6,Candidate_Name:'ဦးသိန်းစိန်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ကဘလ(နိုင်)၁၉၇၇၆၅',Education: 'M.C.Sc',Occupation: 'Lecturer',Permanent_Address: 'ပုဂံ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 23,Party_ID: 3,Candidate_Name:'ဦးကြည်အုံး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1985/8/9',Race: 'ရခိုင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/မရန(နိုင်)၁၉၇၇၆၇',Education: 'M.B.B.S',Occupation: 'Doctor',Permanent_Address: 'မုံရွာ',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 24,Party_ID: 9,Candidate_Name:'ဦးခင်မောင်ရွှေ',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1976/8/8',Race: 'ပအို့',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/မလန(နိုင်)၁၂၆၁၀၁',Education: 'L.B.B.S',Occupation: 'Lawer',Permanent_Address: 'စစ်ကိုင်း',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 25,Party_ID: 2,Candidate_Name:'ဦးညွန့်ဝင်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1989/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/မရန(နိုင်)၁၂၃၄၄၇',Education: 'B.A',Occupation: 'Teacher',Permanent_Address: 'ရွှေဘို',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 26,Party_ID: 7,Candidate_Name:'ဦးအောင်မြင့်',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'မွန်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/စကန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'မန္တလေး',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 27,Party_ID: 5,Candidate_Name:'ဦးအောင်ဌေး',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1986/8/8',Race: 'ရှမ်း',Religion: 'ခရစ်ယာန်',NRIC_No: '၅/ရဘန(နိုင်)၂၃၁၈၉၀',Education: 'B.C.Sc',Occupation: 'Teacher',Permanent_Address: 'နေပြည်တော်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 28,Party_ID: 8,Candidate_Name:'ဦးဇော်ဇော်',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1987/8/7',Race: 'ဗမာ',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/ယမပ(နိုင်)၁၂၅၄၆၈',Education: 'M.C.Sc',Occupation: 'Teacher',Permanent_Address: 'ပြင်ဦးလွင်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 29,Party_ID: 4,Candidate_Name:'ဒေါ်ထက်ထက်ထွန်း',Image: './db/download.jpg',Election_Name: 'Election One',Date_Of_Birth: '1990/8/9',Race: 'ကချင်',Religion: 'ဗုဒ္ဓ',NRIC_No: '၅/တမန(နိုင်)၀၉၈၇၃၇',Education: 'B.C.Sc',Occupation: 'Developer',Permanent_Address: 'မြိတ်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Candidate_ID : 30,Party_ID: 10,Candidate_Name:'ဦးဖြိုးမင်းသိန်း',Image: './db/download.jpg',Election_Name: 'Election Two',Date_Of_Birth: '1988/8/7',Race: 'ဗမာ',Religion: 'ဟိန္ဒူ',NRIC_No: '၅/ပလဘ(နိုင်)၀၉၈၇၄၅',Education: 'M.C.Sc',Occupation: 'Marking Manager',Permanent_Address: 'ပြည်',Why_to_be_a_candidate: 'As the government works toward total electrification by 2030, Asia General Electric Supplies Equipment for home and commercian use that will power Myanmar for decades to come.',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},

]
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('candidate').del()
    .then(function () {
      // Inserts seed entries
      return knex('candidate').insert(candidateList);
    });
};
