const villageList = [
  {Village_ID : 1,Village_Tracts_ID: 2,Village_Code:'175640',Village_Name: 'ထောက်ကြံ့ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 2,Village_Tracts_ID: 2,Village_Code:'173439',Village_Name: 'အောင်သာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 3,Village_Tracts_ID: 3,Village_Code:'171847',Village_Name: 'ကိုးထောင်ဘို့ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 4,Village_Tracts_ID: 3,Village_Code:'171851',Village_Name: 'ကိုင်းမရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 5,Village_Tracts_ID: 4,Village_Code:'174281',Village_Name: 'ချောင်းဝရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 6,Village_Tracts_ID: 4,Village_Code:'217222',Village_Name: 'ထင်းခါးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 7,Village_Tracts_ID: 6,Village_Code:'176086',Village_Name: 'ကင်းတပ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 8,Village_Tracts_ID: 6,Village_Code:'176088',Village_Name: 'မော်လိုက်ကလေးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 9,Village_Tracts_ID: 6,Village_Code:'176087',Village_Name: 'ရှားပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 10,Village_Tracts_ID: 7,Village_Code:'172967',Village_Name: 'ကြေးမုံရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 11,Village_Tracts_ID: 7,Village_Code:'172968',Village_Name: 'ဥသျှစ်ကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 12,Village_Tracts_ID: 7,Village_Code:'172969',Village_Name: 'သိပ္ပံကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 13,Village_Tracts_ID: 8,Village_Code:'171117',Village_Name: 'ကျောက်ဆည်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 14,Village_Tracts_ID: 8,Village_Code:'171118',Village_Name: 'ကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 15,Village_Tracts_ID: 9,Village_Code:'171314',Village_Name: 'ရှားတောရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 16,Village_Tracts_ID: 11,Village_Code:'173705',Village_Name: 'ကြပ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 17,Village_Tracts_ID: 11,Village_Code:'173706',Village_Name: 'သလောက်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 18,Village_Tracts_ID: 11,Village_Code:'173708',Village_Name: 'သစ်ရာပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 19,Village_Tracts_ID: 11,Village_Code:'173707',Village_Name: 'ဝင်းကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 20,Village_Tracts_ID: 10,Village_Code:'176043',Village_Name: 'ရွာသာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 21,Village_Tracts_ID: 1,Village_Code:'176388',Village_Name: 'မင်းဆင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 22,Village_Tracts_ID: 1,Village_Code:'217367',Village_Name: 'မိုလွန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 23,Village_Tracts_ID: 1,Village_Code: '176389',Village_Name: 'နောက်ပဲရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 24,Village_Tracts_ID: 5,Village_Code:'175507',Village_Name: 'တိုက်မွန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 25,Village_Tracts_ID: 5,Village_Code:'175508',Village_Name: 'ကွန်းတောင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 26,Village_Tracts_ID: 5,Village_Code:'175509',Village_Name: 'တိုင်းပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 27,Village_Tracts_ID: 12,Village_Code:'111222',Village_Name: 'ဘောလခဲရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 28,Village_Tracts_ID: 12,Village_Code:'222333',Village_Name: 'ကျွန်းထပ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 29,Village_Tracts_ID: 13,Village_Code:'444555',Village_Name: 'နန်းဖဲရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 30,Village_Tracts_ID: 13,Village_Code:'666777',Village_Name: 'ကွက်သစ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 31,Village_Tracts_ID: 13,Village_Code:'111555',Village_Name: 'သပြေရိုးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 32,Village_Tracts_ID: 14,Village_Code:'121212',Village_Name: 'ဖားဆောင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 33,Village_Tracts_ID: 14,Village_Code:'131313',Village_Name: 'နွယ်ခွေရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 34,Village_Tracts_ID: 15,Village_Code:'141414',Village_Name: 'ဝမ်အောင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 35,Village_Tracts_ID: 15,Village_Code:'151515',Village_Name: 'ကညင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 36,Village_Tracts_ID: 16,Village_Code:'161616',Village_Name: 'အာလမ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 37,Village_Tracts_ID: 17,Village_Code:'181818',Village_Name: 'ကံဆိပ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 38,Village_Tracts_ID: 17,Village_Code:'191919',Village_Name: 'ဇီးအွန်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 39,Village_Tracts_ID: 18,Village_Code:'232323',Village_Name: 'ပန်းမတီးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 40,Village_Tracts_ID: 19,Village_Code:'242424',Village_Name: 'နောင်နန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 41,Village_Tracts_ID: 19,Village_Code:'252525',Village_Name: 'ကံစုရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 42,Village_Tracts_ID: 16,Village_Code:'262626',Village_Name: 'ရွာသစ်စုရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 43,Village_Tracts_ID: 20,Village_Code:'272727',Village_Name: 'ချောင်းဝရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 44,Village_Tracts_ID: 20,Village_Code:'282828',Village_Name: 'ရေကျော်ဝရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 45,Village_Tracts_ID: 18,Village_Code:'292929',Village_Name: 'ကွင်းပုံရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 46,Village_Tracts_ID: 21,Village_Code:'343433',Village_Name: 'အလီအောင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 47,Village_Tracts_ID: 21,Village_Code:'353535',Village_Name: 'ဇရပ်လှရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 48,Village_Tracts_ID: 22,Village_Code:'373737',Village_Name: 'အဝိဝမ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 49,Village_Tracts_ID: 22,Village_Code:'363636',Village_Name: 'အေးချမ်းသာယာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 50,Village_Tracts_ID: 23,Village_Code:'383838',Village_Name: 'မော်ဟန်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 51,Village_Tracts_ID: 23,Village_Code:'393939',Village_Name: 'ပေါ်တော်မူရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 52,Village_Tracts_ID: 24,Village_Code:'454545',Village_Name: 'မပြင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 53,Village_Tracts_ID: 24,Village_Code:'212121',Village_Name: 'အေးစုရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 54,Village_Tracts_ID: 25,Village_Code:'323232',Village_Name: 'ပင်းခါးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 55,Village_Tracts_ID: 25,Village_Code:'434343',Village_Name: 'ကံကြီးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 56,Village_Tracts_ID: 26,Village_Code:'676767',Village_Name: 'ပင့်သာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 57,Village_Tracts_ID: 26,Village_Code:'666121',Village_Name: 'ရေကျော်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 58,Village_Tracts_ID: 27,Village_Code:'989898',Village_Name: 'ရွှေဘုံသာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 59,Village_Tracts_ID: 27,Village_Code:'898989',Village_Name: 'ညီနောင်လေးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 60,Village_Tracts_ID: 28,Village_Code:'535353',Village_Name: 'ရွှေချောင်းသာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 61,Village_Tracts_ID: 28,Village_Code:'636363',Village_Name: 'ပျားရည်စုရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 62,Village_Tracts_ID: 29,Village_Code:'727272',Village_Name: 'မံစံရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 63,Village_Tracts_ID: 29,Village_Code:'828282',Village_Name: 'ရွှေပြည်အေးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 64,Village_Tracts_ID: 30,Village_Code:'929292',Village_Name: 'ဖရဲရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 65,Village_Tracts_ID: 30,Village_Code:'525252',Village_Name: 'သာပေါင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 66,Village_Tracts_ID: 31,Village_Code:'828910',Village_Name: 'ညောင်ပင်သာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  {Village_ID : 67,Village_Tracts_ID: 31,Village_Code:'101987',Village_Name: 'ဘဝသစ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 68,Village_Tracts_ID: 32,Village_Code:'098765',Village_Name: 'သရက်ကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 69,Village_Tracts_ID: 32,Village_Code:'890567',Village_Name: 'သံလွင်ငူရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 70,Village_Tracts_ID: 33,Village_Code:'246158',Village_Name: 'တောင်အင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 71,Village_Tracts_ID: 33,Village_Code:'835300',Village_Name: 'လှေလမ်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 72,Village_Tracts_ID: 34,Village_Code:'987654',Village_Name: 'ဟဲဟိုးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 73,Village_Tracts_ID: 34,Village_Code:'777666',Village_Name: 'ဗောဓိကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 74,Village_Tracts_ID: 35,Village_Code:'234167',Village_Name: 'မြို့သစ်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 75,Village_Tracts_ID: 35,Village_Code:'231415',Village_Name: 'မရမ်းတောရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 76,Village_Tracts_ID: 36,Village_Code:'198765',Village_Name: 'မြင်သာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 77,Village_Tracts_ID: 36,Village_Code:'098234',Village_Name: 'ကူဖြူရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 78,Village_Tracts_ID: 37,Village_Code:'650923',Village_Name: 'မြို့ကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 79,Village_Tracts_ID: 37,Village_Code:'769423',Village_Name: 'မဲကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 80,Village_Tracts_ID: 38,Village_Code:'010101',Village_Name: 'သပြေလှရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 81,Village_Tracts_ID: 38,Village_Code:'887766',Village_Name: 'ထိန်အင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 82,Village_Tracts_ID: 39,Village_Code:'989877',Village_Name: 'အင်ခိုင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 83,Village_Tracts_ID: 39,Village_Code:'918765',Village_Name: 'လယ်တော်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 84,Village_Tracts_ID: 40,Village_Code:'234762',Village_Name: 'ဟန်းကောရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 85,Village_Tracts_ID: 40,Village_Code:'128745',Village_Name: 'မကျီးကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 86,Village_Tracts_ID: 41,Village_Code:'652077',Village_Name: 'မန်ကျီရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 87,Village_Tracts_ID: 41,Village_Code:'003311',Village_Name: 'အင်းသာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 88,Village_Tracts_ID: 42,Village_Code:'995322',Village_Name: 'ရွှေညောင်ပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 89,Village_Tracts_ID: 42,Village_Code:'885544',Village_Name: 'သရက်ချောင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 90,Village_Tracts_ID: 43,Village_Code:'192020',Village_Name: 'ဘုရားဖြူရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 91,Village_Tracts_ID: 43,Village_Code:'928272',Village_Name: 'ရွှေချောင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 92,Village_Tracts_ID: 44,Village_Code:'827288',Village_Name: 'ငွေတောင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 93,Village_Tracts_ID: 44,Village_Code:'252566',Village_Name: 'ရွှေပန်းတောရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 94,Village_Tracts_ID: 45,Village_Code:'109272',Village_Name: 'ကုန်းသာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 95,Village_Tracts_ID: 45,Village_Code:'758594',Village_Name: 'ထန်းကိုးပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 96,Village_Tracts_ID: 46,Village_Code:'709665',Village_Name: 'ကြာအင်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 97,Village_Tracts_ID: 46,Village_Code:'747575',Village_Name: 'ညောင်ပင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 98,Village_Tracts_ID: 47,Village_Code:'876532',Village_Name: 'ဆင်ကူးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 99,Village_Tracts_ID: 47,Village_Code:'992211',Village_Name: 'မြကန်သာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 100,Village_Tracts_ID: 48,Village_Code:'111999',Village_Name: 'ရေတံခွန်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 101,Village_Tracts_ID: 48,Village_Code:'231765',Village_Name: 'သာဂလာရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 102,Village_Tracts_ID: 49,Village_Code:'819265',Village_Name: 'သာယာကုန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 103,Village_Tracts_ID: 49,Village_Code:'432180',Village_Name: 'ပိတောက်မြိုင်ရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 104,Village_Tracts_ID: 50,Village_Code:'985432',Village_Name: 'ဝဲကြီးရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  // {Village_ID : 105,Village_Tracts_ID: 50,Village_Code:'009944',Village_Name: 'ကုန်းတန်းရွာ',Created_By: 'mmk',Updated_By: 'mmm',Status:'Active',Remark:''},
  
]
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('village').del()
    .then(function () {
      // Inserts seed entries
      return knex('village').insert(villageList);
    });
};
