const nrcList = [
  { id: 1, code: '၁/အဂယ(နိုင်)', townshipname: 'အင်ဂျန်းယန်းမြို့နယ်'},
  { id: 1, code: '၁/ဗမန(နိုင်)', townshipname: 'ဗန်းမော်မြို့နယ်'},
  { id: 1, code: '၁/မကန(နိုင်)', townshipname: 'မြစ်ကြီးနားမြို့နယ်'},
  { id: 1, code: '၁/မခဘ(နိုင်)', townshipname: 'မချမ်း‌ဘောမြို့နယ်'},
  { id: 1, code: '၁/မမန(နိုင်)', townshipname: 'မိုးမောက်မြို့နယ်'},
  { id: 1, code: '၁/နမန(နိုင်)', townshipname: 'နောင်မွန်မြို့နယ်'},
  { id: 1, code: '၁/မညန(နိုင်)', townshipname: 'မိုးညှင်းမြို့နယ်'},
  { id: 1, code: '၁/မစန(နိုင်)', townshipname: 'မံစီမြို့နယ်'},
  { id: 1, code: '၁/ပတအ(နိုင်)', townshipname: 'ပူတာအိုမြို့နယ်'},
  { id: 1, code: '၁/ဆပဘ(နိုင်)', townshipname: 'ဆွမ်ပရာဘွမ်မြို့နယ်'},
  { id: 1, code: '၁/ဝမန(နိုင်)', townshipname: 'ဝိုင်း‌မော်မြို့နယ်'},
  { id: 1, code: '၁/ရကန(နိုင်)', townshipname: '‌‌‌‌‌‌‌ရွှေကူမြို့နယ်'},
  { id: 1, code: '၁/ခလဖ(နိုင်)', townshipname: '‌‌ခေါင်လန်ဖူးမြို့နယ်'},

  { id: 1, code: '၁/ဖကန(နိုင်)', townshipname: 'ဖားကန့်မြို့နယ်'},
  { id: 1, code: '၁/ဆလန(နိုင်)', townshipname: '‌ဆော့လော်မြို့နယ်'},
  { id: 1, code: '၁/တနန(နိုင်)', townshipname: 'တနိုင်းမြို့နယ်'},

  { id: 1, code: '၁/ဒဖယ(နိုင်)', townshipname: 'ဒေါ့ဖုန်းယန်မြို့နယ်'},
  { id: 1, code: '၁/ဟပန(နိုင်)', townshipname: 'ဟိုပင်မြို့နယ်'},
  { id: 1, code: '၁/ကမန(နိုင်)', townshipname: 'ကာမိုင်းမြို့နယ်'},
  { id: 1, code: '၁/ပနဒ(နိုင်)', townshipname: 'ပန်နန်းဒင်ဒင်မြို့နယ်'},
  { id: 1, code: '၁/ခဖန(နိုင်)', townshipname: 'ချီဖွေမြို့နယ်'},
  { id: 1, code: '၁/လဂန(နိုင်)', townshipname: 'လွယ်ဂျယ်မြို့နယ်'},
  { id: 1, code: '၁/ကပတ(နိုင်)', townshipname: 'ကန်ပိုက်တီမြို့နယ်'},
  { id: 1, code: '၁/ဆဒန(နိုင်)', townshipname: 'ဆဒုံးမြို့နယ်'},
  { id: 1, code: '၁/ရဗယ(နိုင်)', townshipname: 'ရှင်ဗွေယန်မြို့နယ်'},
  { id: 1, code: '၁/ပဝန(နိုင်)', townshipname: 'ပန်ဝါမြို့နယ်'},
  { id: 1, code: '၁/မလန(နိုင်)', townshipname: 'မြို့လှမြို့နယ်'},


  { id: 1, code: '၁/ခဘဒ(နိုင်)', townshipname: 'ခဘဒ'},
  { id: 1, code: '၁/မကတ(နိုင်)', townshipname: 'မကတ'},
  { id: 1, code: '၁/ကမတ(နိုင်)', townshipname: 'ကမတ'},
  { id: 1, code: '၁/ဆဘန(နိုင်)', townshipname: 'ဆဘန'},
  { id: 1, code: '၁/ဆဘတ(နိုင်)', townshipname: 'ဆဘတ'},
  { id: 1, code: '၁/ဘဂန(နိုင်)', townshipname: 'ဘဂန'},
  { id: 1, code: '၁/အကယ(နိုင်)', townshipname: 'အကယ'},
  
  

  { id: 2, code: '၂/ဘလခ(နိုင်)', townshipname: 'ဘော်လခဲမြို့နယ်'},
  { id: 2, code: '၂/ဒမဆ(နိုင်)', townshipname: 'ဒီ‌မောဆိုးမြို့နယ်'},
  { id: 2, code: '၂/လကန(နိုင်)', townshipname: 'လွိုင်‌ကော်မြို့နယ်'},
  { id: 2, code: '၂/မစန(နိုင်)', townshipname: 'မယ်စဲမြို့နယ်'},
  { id: 2, code: '၂/ဖဆန(နိုင်)', townshipname: 'ဖားဆောင်းမြို့နယ်'},
  { id: 2, code: '၂/ဖရဆ(နိုင်)', townshipname: 'ဖရူးဆိုးမြို့နယ်'},
  { id: 2, code: '၂/ရတန(နိုင်)', townshipname: 'ရှားတောမြို့နယ်'},
  { id: 2, code: '၂/ရသန(နိုင်)', townshipname: 'ရွာသစ်မြို့နယ်'},

  { id: 3, code: '၃/လဘန(နိုင်)', townshipname: 'လွိုင်းဘွဲ့မြို့နယ်'},
  { id: 3, code: '၃/ဘအန(နိုင်)', townshipname: 'ဘားအံ့မြို့နယ်'},
  { id: 3, code: '၃/ဖပန(နိုင်)', townshipname: 'ဖာပွန်မြို့နယ်'},
  { id: 3, code: '၃/ကကရ(နိုင်)', townshipname: 'ကော့ကရိတ်မြို့နယ်'},
  { id: 3, code: '၃/ကအဆ(နိုင်)', townshipname: 'ကြာအင်းဆိပ်ကြီးမြို့နယ်'},
  { id: 3, code: '၃/မဝတ(နိုင်)', townshipname: 'မြဝတီမြို့နယ်'},
  { id: 3, code: '၃/သတက(နိုင်)', townshipname: 'သံ‌တောင်ကြီးမြို့နယ်'},
  { id: 3, code: '၃/ဘသဆ(နိုင်)', townshipname: 'ဘုရားသုံးဆူမြို့နယ်'},
  { id: 3, code: '၃/ပကန(နိုင်)', townshipname: 'ပိုင်ကျုံမြို့နယ်'}, 
  { id: 3, code: '၃/လသန(နိုင်)', townshipname: 'လိပ်သိုမြို့နယ်'},
  { id: 3, code: '၃/ရရသ(နိုင်)', townshipname: 'ရှမ်းရွာသစ်မြို့နယ်'},
  { id: 3, code: '၃/ဘဂလ(နိုင်)', townshipname: 'ဘောဂလိမြို့နယ်'},
  { id: 3, code: '၃/ကမမ(နိုင်)', townshipname: 'ကမမောင်းမြို့နယ်'},
  { id: 3, code: '၃/စကလ(နိုင်)', townshipname: 'စုကလိမြို့နယ်'},
  { id: 3, code: '၃/ဝလမ(နိုင်)', townshipname: '၀ေါလေမြိုင်မြို့နယ်'},
  

  { id: 3, code: '၃/ကဆက(နိုင်)', townshipname: 'ကဆက'},
  { id: 3, code: '၃/ကဒန(နိုင်)', townshipname: 'ကဒန'},
  { id: 3, code: '၃/ကအက(နိုင်)', townshipname: 'ကအက'},
  
  
  

  { id: 4, code: '၄/ဖလန(နိုင်)', townshipname: 'ဖလမ်းမြို့နယ်'},
  { id: 4, code: '၄/ဟခန(နိုင်)', townshipname: 'ဟားခါးမြို့နယ်'},
  { id: 4, code: '၄/ထတလ(နိုင်)', townshipname: 'ထန်တလန်မြို့နယ်'},
  { id: 4, code: '၄/ကပလ(နိုင်)', townshipname: 'ကန်ပက်လက်မြို့နယ်'},
  { id: 4, code: '၄/မတပ(နိုင်)', townshipname: 'မတူပီမြို့နယ်'},
  { id: 4, code: '၄/မတန(နိုင်)', townshipname: 'မင်းတပ်မြို့နယ်'},
  { id: 4, code: '၄/ပလဝ(နိုင်)', townshipname: 'ပလက်ဝမြို့နယ်'},
  { id: 4, code: '၄/တတန(နိုင်)', townshipname: 'တီးတိန်မြို့နယ်'},
  { id: 4, code: '၄/တဇန(နိုင်)', townshipname: 'တွန်းဇံမြို့နယ်'},
  { id: 4, code: '၄/ကခန(နိုင်)', townshipname: 'ကျီးခါးမြို့နယ်'},
  { id: 4, code: '၄/ရခဒ(နိုင်)', townshipname: 'ရိခေါ်ဒါရ်မြို့နယ်'},
  { id: 4, code: '၄/ရဇန(နိုင်)', townshipname: 'ရေဇွာမြို့နယ်'},
  { id: 4, code: '၄/ဆမန(နိုင်)', townshipname: 'ဆမီးမြို့နယ်'},


  { id: 5, code: '၅/အရတ(နိုင်)', townshipname: 'အရာ‌တော်မြို့နယ်'},
  { id: 5, code: '၅/ဗမန(နိုင်)', townshipname: 'ဗန်းမောက်မြို့နယ်'},
  { id: 5, code: '၅/ဘတလ(နိုင်)', townshipname: 'ဘုတလင်မြို့နယ်'},
  { id: 5, code: '၅/ခဥတ(နိုင်)', townshipname: 'ချောင်းဦးမြို့နယ်'},
  { id: 5, code: '၅/ခတန(နိုင်)', townshipname: 'ခန္တီးမြို့နယ်'},
  { id: 5, code: '၅/ဟမလ(နိုင်)', townshipname: 'ဟုမ္မလင်းမြို့နယ်'},
  { id: 5, code: '၅/အတန(နိုင်)', townshipname: 'အင်းတော်မြို့နယ်'},
  { id: 5, code: '၅/ကလတ(နိုင်)', townshipname: 'ကလေးမြို့နယ်'},
  { id: 5, code: '၅/ကလဝ(နိုင်)', townshipname: 'ကလေးဝမြို့နယ်'},
  { id: 5, code: '၅/ကဘလ(နိုင်)', townshipname: 'ကန့်ဘလူမြို့နယ်'},
  { id: 5, code: '၅/ကနန(နိုင်)', townshipname: 'ကနီမြို့နယ်'},
  { id: 5, code: '၅/ကလန(နိုင်)', townshipname: 'ကောလင်းမြို့နယ်'},
  { id: 5, code: '၅/ခဥန(နိုင်)', townshipname: 'ခင်ဦးမြို့နယ်'},
  { id: 5, code: '၅/လရန(နိုင်)', townshipname: 'လေရှီးမြို့နယ်'},
  { id: 5, code: '၅/လဟန(နိုင်)', townshipname: 'လဟယ်မြို့နယ်'},
  { id: 5, code: '၅/မလန(နိုင်)', townshipname: 'မော်လိုက်မြို့နယ်'},
  { id: 5, code: '၅/မကန(နိုင်)', townshipname: 'မင်းကင်းမြို့နယ်'},
  { id: 5, code: '၅/မရန(နိုင်)', townshipname: 'မုံရွာမြို့နယ်'},
  { id: 5, code: '၅/မမန(နိုင်)', townshipname: 'မြောင်မြို့နယ်'},
  { id: 5, code: '၅/မမတ(နိုင်)', townshipname: 'မြင်းမူမြို့နယ်'},
  { id: 5, code: '၅/နယန(နိုင်)', townshipname: 'နန်းယွန်းမြို့နယ်'},
  { id: 5, code: '၅/ပလန(နိုင်)', townshipname: 'ပုလဲမြို့နယ်'},
  { id: 5, code: '၅/ဖပန(နိုင်)', townshipname: 'ဖောင်းပြင်မြို့နယ်'},
  { id: 5, code: '၅/ပလဘ(နိုင်)', townshipname: 'ပင်လယ်ဘူးမြို့နယ်'},
  { id: 5, code: '၅/စကန(နိုင်)', townshipname: 'စစ်ကိုင်းမြို့နယ်'},
  { id: 5, code: '၅/ဆလက(နိုင်)', townshipname: 'ဆားလင်းကြီးမြို့နယ်'},
  { id: 5, code: '၅/ရဘန(နိုင်)', townshipname: 'ရွှေဘိုမြို့နယ်'},
  { id: 5, code: '၅/ဒပယ(နိုင်)', townshipname: 'ဒီပဲယင်းမြို့နယ်'},
  { id: 5, code: '၅/တမန(နိုင်)', townshipname: 'တမူးမြို့နယ်'},
  { id: 5, code: '၅/တဆန(နိုင်)', townshipname: 'တန့်ဆည်မြို့နယ်'},
  { id: 5, code: '၅/ထခန(နိုင်)', townshipname: 'ထီချိုင့်မြို့နယ်'},
  { id: 5, code: '၅/ဝလန(နိုင်)', townshipname: 'ဝက်လက်မြို့နယ်'},
  { id: 5, code: '၅/ဝသန(နိုင်)', townshipname: 'ဝန်းသိုမြို့နယ်'},
  { id: 5, code: '၅/ယမပ(နိုင်)', townshipname: 'ယင်းမာပင်မြို့နယ်'},
  { id: 5, code: '၅/ရဥန(နိုင်)', townshipname: 'ရေဦးမြို့နယ်'},
  { id: 5, code: '၅/ကမန(နိုင်)', townshipname: 'ကျောက်မြောင်းမြို့နယ်'},
  { id: 5, code: '၅/မသန(နိုင်)', townshipname: 'မြို့သစ်မြို့နယ်'},  
  { id: 5, code: '၅/ပဆန(နိုင်)', townshipname: 'ပန်ဆောင်မြို့နယ်'},
  { id: 5, code: '၅/ခပန(နိုင်)', townshipname: 'ခမ်းပါတ်မြို့နယ်'},
  { id: 5, code: '၅/မပလ(နိုင်)', townshipname: 'မိုပိုင်းလွတ်မြို့နယ်'},
  { id: 5, code: '၅/ထပခ(နိုင်)', townshipname: 'ထန်ပါခွေမြို့နယ်'},
  { id: 5, code: '၅/ဒဟန(နိုင်)', townshipname: 'ဒုံဟီးမြို့နယ်'},
  { id: 5, code: '၅/ဆမရ(နိုင်)', townshipname: 'ဆွမ္မရာမြို့နယ်'},
  
  { id: 5, code: '၅/ကခထ(နိုင်)', townshipname: 'ကခထ'}, 
  { id: 5, code: '၅/ကပန(နိုင်)', townshipname: 'ကပန'}, 
  { id: 5, code: '၅/စကတ(နိုင်)', townshipname: 'စကတ'},  
  { id: 5, code: '၅/ရဗန(နိုင်)', townshipname: 'ရဗန'},
  

  { id: 6, code: '၆/ဘပန(နိုင်)', townshipname: 'ဘုတ်ပြင်းမြို့နယ်'},
  { id: 6, code: '၆/ထဝန(နိုင်)', townshipname: 'ထားဝယ်မြို့နယ်'},
  { id: 6, code: '၆/ကသန(နိုင်)', townshipname: 'ကော့သောင်းမြို့နယ်'},
  { id: 6, code: '၆/ကစန(နိုင်)', townshipname: 'ကျွန်းစုမြို့နယ်'},
  { id: 6, code: '၆/လလန(နိုင်)', townshipname: 'လောင်းလုံမြို့နယ်'},
  { id: 6, code: '၆/မမန(နိုင်)', townshipname: 'မြိတ်မြို့နယ်'},
  { id: 6, code: '၆/ပလန(နိုင်)', townshipname: 'ပုလောမြို့နယ်'},
  { id: 6, code: '၆/တသရ(နိုင်)', townshipname: 'တနင်္သာရိမြို့နယ်'},
  { id: 6, code: '၆/သရခ(နိုင်)', townshipname: 'သရက်ချောင်းမြို့နယ်'},
  { id: 6, code: '၆/ရဖန(နိုင်)', townshipname: 'ရေဖြူးမြို့နယ်'},
  { id: 6, code: '၆/ကရရ(နိုင်)', townshipname: 'ကရသူရိမြို့နယ်'},
  { id: 6, code: '၆/ခမက(နိုင်)', townshipname: 'ခမောက်ကြီးမြို့နယ်'},
  { id: 6, code: '၆/မတန(နိုင်)', townshipname: 'မေတ္တာမြို့နယ်'},
  { id: 6, code: '၆/ကလအ(နိုင်)', townshipname: 'ကလိန်အောင်မြို့နယ်'},
  { id: 6, code: '၆/ပကမ(နိုင်)', townshipname: 'ပြည်ကြီးမဏ္ဍိုင်မြို့နယ်'},

  { id: 6, code: '၆/ကဆန(နိုင်)', townshipname: 'ကဆန'},
  { id: 6, code: '၆/မအန(နိုင်)', townshipname: 'မအန'},
  { id: 6, code: '၆/ပလတ(နိုင်)', townshipname: 'ပလတ'},
  { id: 6, code: '၆/တနသ(နိုင်)', townshipname: 'တနသ'},


  { id: 7, code: '၇/ပခန(နိုင်)', townshipname: 'ပဲခူးမြို့နယ်'},
  { id: 7, code: '၇/ဒဥန(နိုင်)', townshipname: 'ဒိုက်ဦးမြို့နယ်'},
  { id: 7, code: '၇/ကဝန(နိုင်)', townshipname: 'ကဝမြို့နယ်'},
  { id: 7, code: '၇/ကကန(နိုင်)', townshipname: 'ကျောက်ကြီးမြို့နယ်'},
  { id: 7, code: '၇/ကတခ(နိုင်)', townshipname: '‌ကျောက်တံခါးမြို့နယ်'},
  { id: 7, code: '၇/ညလပ(နိုင်)', townshipname: 'ညောင်လေးပင်မြို့နယ်'},
  { id: 7, code: '၇/အတန(နိုင်)', townshipname: 'အုတ်တွင်းမြို့နယ်'},
  { id: 7, code: '၇/ဖမန(နိုင်)', townshipname: 'ဖြူးမြို့နယ်'},
  { id: 7, code: '၇/ရကန(နိုင်)', townshipname: 'ရွှေကျင်မြို့နယ်'},
  { id: 7, code: '၇/ထတပ(နိုင်)', townshipname: 'ထန်းတပင်မြို့နယ်'},
  { id: 7, code: '၇/တငန(နိုင်)', townshipname: 'တောင်ငူမြို့နယ်'},
  { id: 7, code: '၇/သနပ(နိုင်)', townshipname: 'သနပ်ပင်မြို့နယ်'},
  { id: 7, code: '၇/ဝမန(နိုင်)', townshipname: '‌‌‌‌‌‌‌၀ေါမြို့နယ်'},
  { id: 7, code: '၇/ရတရ(နိုင်)', townshipname: 'ရေတာရှည်မြို့နယ်'},
  { id: 7, code: '၇/ကပက(နိုင်)', townshipname: 'ကြို့ပင်ကောက်မြို့နယ်'},
  { id: 7, code: '၇/လပတ(နိုင်)', townshipname: 'လက်ပံတန်းမြို့နယ်'},
  { id: 7, code: '၇/မလန(နိုင်)', townshipname: 'မင်းလှမြို့နယ်'},
  { id: 7, code: '၇/မညန(နိုင်)', townshipname: 'မိုးညိုမြို့နယ်'},
  { id: 7, code: '၇/နတလ(နိုင်)', townshipname: 'နတ်တလင်းမြို့နယ်'},
  { id: 7, code: '၇/အဖန(နိုင်)', townshipname: 'အုတ်ဖိုမြို့နယ်'},
  { id: 7, code: '၇/ပတန(နိုင်)', townshipname: 'ပန်းတောင်းမြို့နယ်'},
  { id: 7, code: '၇/ပခတ(နိုင်)', townshipname: 'ပေါက်ခေါင်းမြို့နယ်'},
  { id: 7, code: '၇/ပတတ(နိုင်)', townshipname: 'ပေါင်းတည်မြို့နယ်'},
  { id: 7, code: '၇/ပမန(နိုင်)', townshipname: 'ပြည်မြို့နယ်'},
  { id: 7, code: '၇/ရတန(နိုင်)', townshipname: 'ရွှေတောင်မြို့နယ်'},
  { id: 7, code: '၇/သဝတ(နိုင်)', townshipname: 'သာယာဝတီမြို့နယ်'},
  { id: 7, code: '၇/သကန(နိုင်)', townshipname: 'သဲကုန်းမြို့နယ်'},
  { id: 7, code: '၇/ဇကန(နိုင်)', townshipname: 'ဇီးကုန်းမြို့နယ်'},
  { id: 7, code: '၇/ဖဒန(နိုင်)', townshipname: 'ဖဒိုမြို့နယ်'},  
  
  
  
  { id: 8, code: '၈/အလန(နိုင်)', townshipname: 'အောင်လံမြို့နယ်'},
  { id: 8, code: '၈/ခမန(နိုင်)', townshipname: 'ချောက်မြို့နယ်'},
  { id: 8, code: '၈/ဂဂန(နိုင်)', townshipname: 'ဂန့်‌‌ဂေါမြို့နယ်'},
  { id: 8, code: '၈/ကမန(နိုင်)', townshipname: 'ကံမမြို့နယ်'},
  { id: 8, code: '၈/မကန(နိုင်)', townshipname: 'မကွေးမြို့နယ်'},
  { id: 8, code: '၈/မဘန(နိုင်)', townshipname: 'မင်းဘူးမြို့နယ်'},
  { id: 8, code: '၈/မတန(နိုင်)', townshipname: 'မင်းတုန်းမြို့နယ်'},
  { id: 8, code: '၈/မလန(နိုင်)', townshipname: 'မင်းလှမြို့နယ်'},
  { id: 8, code: '၈/မမန(နိုင်)', townshipname: 'မြိုင်မြို့နယ်'},
  { id: 8, code: '၈/မသန(နိုင်)', townshipname: 'မြို့သစ်မြို့နယ်'},
  { id: 8, code: '၈/နမန(နိုင်)', townshipname: 'နတ်မောက်မြို့နယ်'},
  { id: 8, code: '၈/ငဖန(နိုင်)', townshipname: 'ငဖဲမြို့နယ်'},
  { id: 8, code: '၈/ပခက(နိုင်)', townshipname: 'ပခုက္ကူမြို့နယ်'},
  { id: 8, code: '၈/ပမန(နိုင်)', townshipname: 'ပေါက်မြို့နယ်'},
  { id: 8, code: '၈/ပဖန(နိုင်)', townshipname: 'ပွင့်ဖြူမြို့နယ်'},
  { id: 8, code: '၈/စလန(နိုင်)', townshipname: 'စလင်းမြို့နယ်'},
  { id: 8, code: '၈/ဆမန(နိုင်)', townshipname: 'ဆောမြို့နယ်'},
  { id: 8, code: '၈/ဆဖန(နိုင်)', townshipname: 'ဆိပ်ဖြူမြို့နယ်'},
  { id: 8, code: '၈/စတရ(နိုင်)', townshipname: 'စေတုတ္တတရာမြိူ့နယ်'},
  { id: 8, code: '၈/ဆပဝ(နိုင်)', townshipname: 'ဆင်ပေါင်ဝဲမြို့နယ်'},
  { id: 8, code: '၈/တတက(နိုင်)', townshipname: 'တောင်းတွင်းကြီး'},
  { id: 8, code: '၈/သရန(နိုင်)', townshipname: 'သရက်မြို့နယ်'},
  { id: 8, code: '၈/ထလန(နိုင်)', townshipname: 'ထီးလင်းမြို့နယ်'},
  { id: 8, code: '၈/ရနခ(နိုင်)', townshipname: 'ရေနံချောင်းမြို့နယ်'},
  { id: 8, code: '၈/ရစက(နိုင်)', townshipname: 'ရေစကြိုမြို့နယ်'},
  { id: 8, code: '၈/ကထန(နိုင်)', townshipname: 'ကျောက်ထုမြို့နယ်'},

  { id: 8, code: '၈/မထန(နိုင်)', townshipname: 'မထန'},
  
  { id: 8, code: '၈/ခမက(နိုင်)', townshipname: 'ခမက'},
  

  { id: 9, code: '၉/အမရ(နိုင်)', townshipname: 'အမရပူရမြို့နယ်'},
  { id: 9, code: '၉/အမဇ(နိုင်)', townshipname: 'အောင်မြေသာဇံမြို့နယ်'},
  { id: 9, code: '၉/ခအဇ(နိုင်)', townshipname: 'ချမ်းအေးသာဇံမြို့နယ်'},
  { id: 9, code: '၉/ခမစ(နိုင်)', townshipname: 'ချမ်းမြသာစည်မြို့နယ်'},
  { id: 9, code: '၉/ကပတ(နိုင်)', townshipname: 'ကျောက်ပန်းတောင်းမြို့နယ်'},
  { id: 9, code: '၉/ကဆန(နိုင်)', townshipname: 'ကျောက်ဆည််မြို့နယ်'},
  { id: 9, code: '၉/လဝန(နိုင်)', townshipname: 'လယ်‌‌‌၀ေးမြို့နယ်'},
  { id: 9, code: '၉/မတရ(နိုင်)', townshipname: 'မတ္တရာမြို့နယ်'},
  { id: 9, code: '၉/မဟမ(နိုင်)', townshipname: 'မဟာအောင်မြေမြို့နယ်'},
  { id: 9, code: '၉/မလန(နိုင်)', townshipname: 'မလှိုင်မြို့နယ်'},
  { id: 9, code: '၉/မထလ(နိုင်)', townshipname: 'မိတ္ထီလာမြို့နယ်'},
  { id: 9, code: '၉/မကန(နိုင်)', townshipname: 'မိုးကုတ်မြို့နယ်'},
  { id: 9, code: '၉/မခန(နိုင်)', townshipname: 'မြင်းခြံမြို့နယ်'},
  { id: 9, code: '၉/မသန(နိုင်)', townshipname: 'မြစ်သားမြို့နယ်'},
  { id: 9, code: '၉/နထက(နိုင်)', townshipname: 'နွားထိုးကြီးမြို့နယ်'},
  { id: 9, code: '၉/ငဇန(နိုင်)', townshipname: 'ငါန်းဇွန်မြို့နယ်'},
  { id: 9, code: '၉/ညဥန(နိုင်)', townshipname: 'ညောင်းဦးမြို့နယ်'},
  { id: 9, code: '၉/ပသက(နိုင်)', townshipname: 'ပုသိမ်ကြီးမြို့နယ်'},
  { id: 9, code: '၉/ပဘန(နိုင်)', townshipname: 'ပျော်ဘွယ်မြို့နယ်'},
  { id: 9, code: '၉/ပကခ(နိုင်)', townshipname: 'ပြည်ကြီးတံခွန်မြို့နယ်'},
  { id: 9, code: '၉/ပမန(နိုင်)', townshipname: 'ပျဥ်းမနားမြို့နယ်'},
  { id: 9, code: '၉/ပဥလ(နိုင်)', townshipname: 'ပြင်ဦးလွင်မြို့နယ်'},
  { id: 9, code: '၉/စကန(နိုင်)', townshipname: 'စဥ့်ကူမြို့နယ်'},
  { id: 9, code: '၉/စကတ(နိုင်)', townshipname: 'စဥ့်ကိုင်မြို့နယ်'},
  { id: 9, code: '၉/တတဥ(နိုင်)', townshipname: 'တံတားဦးမြို့နယ်'},
  { id: 9, code: '၉/တသန(နိုင်)', townshipname: 'တောင်သာမြို့နယ်'},
  { id: 9, code: '၉/သပက(နိုင်)', townshipname: 'သပိတ်ကျင်းမြို့နယ်'},
  { id: 9, code: '၉/သစန(နိုင်)', townshipname: 'သာစည်မြို့နယ်'},
  { id: 9, code: '၉/ဝတန(နိုင်)', townshipname: 'ဝမ်းတွင်းမြို့နယ်'},
  { id: 9, code: '၉/ရမသ(နိုင်)', townshipname: 'ရမည်းသင်းမြို့နယ်'},
  { id: 9, code: '၉/ငသရ(နိုင်)', townshipname: 'ငါ့သရောက်မြို့နယ်'},
  { id: 9, code: '၉/တကန(နိုင်)', townshipname: 'တကောင်းမြို့နယ်'},

  { id: 9, code: '၉/မမန(နိုင်)', townshipname: 'မမန'},
  { id: 9, code: '၉/မနမ(နိုင်)', townshipname: 'မနမ'},
  { id: 9, code: '၉/မနတ(နိုင်)', townshipname: 'မနတ'}, 
  { id: 9, code: '၉/မရမ(နိုင်)', townshipname: 'မရမ'},
  { id: 9, code: '၉/မရတ(နိုင်)', townshipname: 'မရတ'},
  { id: 9, code: '၉/တကတ(နိုင်)', townshipname: 'တပ်ကုန်းမြို့နယ်'},
  { id: 9, code: '၉/ဒခသ(နိုင်)', townshipname: 'ဒခသ'},
  { id: 9, code: '၉/ဥတတ(နိုင်)', townshipname: 'ဥတတ'},
  { id: 9, code: '၉/ပဗသ(နိုင်)', townshipname: 'ပုဗ္ဗသီရိမြို့နယ်'},
  { id: 9, code: '၉/ဇဗသ(နိုင်)', townshipname: 'ဇမ္ဗူသီရိမြို့နယ်'},
  { id: 9, code: '၉/ဇယသ(နိုင်)', townshipname: 'ဇေယျာသီရိမြို့နယ်'},
  { id: 9, code: '၉/ဒခရ(နိုင်)', townshipname: 'ဒက္ခိဏသီရိမြို့နယ်'},
  { id: 9, code: '၉/ဥတရ(နိုင်)', townshipname: 'ဥတ္တရသီရိမြို့နယ်'},

  { id: 10, code: '၁၀/ဘလန(နိုင်)', townshipname: 'ဘီးလင်းမြို့နယ်'},
  { id: 10, code: '၁၀/ခဆန(နိုင်)', townshipname: 'ချောင်းဆုံမြို့နယ်'},
  { id: 10, code: '၁၀/ကမရ(နိုင်)', townshipname: 'ကျုက်မရောမြို့နယ်'},
  { id: 10, code: '၁၀/ကထန(နိုင်)', townshipname: 'ကျိုက်ထိုမြို့နယ်'},
  { id: 10, code: '၁၀/မလမ(နိုင်)', townshipname: 'မော်လမြိုင်မြို့နယ်'},
  { id: 10, code: '၁၀/မဒန(နိုင်)', townshipname: 'မုဒုံမြို့နယ်'},
  { id: 10, code: '၁၀/ပမန(နိုင်)', townshipname: 'ပေါင်မြို့နယ်'},
  { id: 10, code: '၁၀/သဖရ(နိုင်)', townshipname: 'သံဖြူဇရပ်မြို့နယ်'},
  { id: 10, code: '၁၀/သထန(နိုင်)', townshipname: 'သထုံမြို့နယ်'},
  { id: 10, code: '၁၀/ရမန(နိုင်)', townshipname: 'ရေးမြို့နယ်'},
  { id: 10, code: '၁၀/ခဇန(နိုင်)', townshipname: 'ခေါဇာမြို့နယ်'},
  { id: 10, code: '၁၀/လမန(နိုင်)', townshipname: 'လမိုင်းမြို့နယ်'},

  { id: 11, code: '၁၁/အမန(နိုင်)', townshipname: 'အမ်းမြို့နယ်'},
  { id: 11, code: '၁၁/ဘသတ(နိုင်)', townshipname: 'ဘူးသီးတောင်မြို့နယ်'},
  { id: 11, code: '၁၁/ဂမန(နိုင်)', townshipname: 'ဂွမြို့နယ်'},
  { id: 11, code: '၁၁/ကတလ(နိုင်)', townshipname: 'ကျိန္တလိမြို့နယ်'},
  { id: 11, code: '၁၁/ကဖန(နိုင်)', townshipname: 'ကျောက်ဖြူမြို့နယ်'},
  { id: 11, code: '၁၁/ကတန(နိုင်)', townshipname: 'ကျောက်တော်မြို့နယ်'},
  { id: 11, code: '၁၁/မအန(နိုင်)', townshipname: 'မာန်အောင်မြို့နယ်'},
  { id: 11, code: '၁၁/မအတ(နိုင်)', townshipname: 'မအီမြို့နယ်'},
  { id: 11, code: '၁၁/မပတ(နိုင်)', townshipname: 'မြေပုံမြို့နယ်'},
  { id: 11, code: '၁၁/မဥန(နိုင်)', townshipname: 'မြောက်ဦးမြို့နယ်'},
  { id: 11, code: '၁၁/မပန(နိုင်)', townshipname: 'မင်းပြားမြို့နယ်'},
  { id: 11, code: '၁၁/မတန(နိုင်)', townshipname: 'မောင်တောမြို့နယ်'},
  { id: 11, code: '၁၁/ပဏက(နိုင်)', townshipname: 'ပုဏ္ကားကျွန်းမြို့နယ်'},
  { id: 11, code: '၁၁/ပတန(နိုင်)', townshipname: 'ပေါက်တောမြို့နယ်'},
  { id: 11, code: '၁၁/စတန(နိုင်)', townshipname: 'စစ်တွေမြို့နယ်'},
  { id: 11, code: '၁၁/တကန(နိုင်)', townshipname: 'တောင်ကုတ်မြို့နယ်'},
  { id: 11, code: '၁၁/သတန(နိုင်)', townshipname: 'သံတွဲမြို့နယ်'},
  { id: 11, code: '၁၁/ရဗန(နိုင်)', townshipname: 'ရမ်းဗြဲမြို့နယ်'},
  { id: 11, code: '၁၁/ရသတ(နိုင်)', townshipname: 'ရသေ့တောင်မြို့နယ်'},
  { id: 11, code: '၁၁/တပဝ(နိုင်)', townshipname: 'တောင်ပြိုလက်၀ဲမြို့နယ်'},

  { id: 12, code: '၁၂/အလန(နိုင်)', townshipname: 'အလုံမြို့နယ်'},
  { id: 12, code: '၁၂/ဗဟန(နိုင်)', townshipname: 'ဗဟန်းမြို့နယ်'},
  { id: 12, code: '၁၂/ဗတထ(နိုင်)', townshipname: 'ဗိုလ်တထောင်မြို့နယ်'},
  { id: 12, code: '၁၂/ကကက(နိုင်)', townshipname: 'ကိုကိုးကျွန်းမြို့နယ်'},
  { id: 12, code: '၁၂/ဒဂမ(နိုင်)', townshipname: 'ဒဂုံမြို့သစ်(မြောက်ပိုင်း)'},
  { id: 12, code: '၁၂/ဒဂန(နိုင်)', townshipname: 'ဒဂုံမြို့သစ်(အနောက်က်ပိုင်း)'},
  { id: 12, code: '၁၂/ဒဂဆ(နိုင်)', townshipname: 'ဒဂုံမြို့သစ်ဆိပ်ကမ်း'},
  { id: 12, code: '၁၂/ဒဂတ(နိုင်)', townshipname: 'ဒဂုံမြို့သစ်(တောင်င်ပိုင်း)'},
  { id: 12, code: '၁၂/ဒဂရ(နိုင်)', townshipname: 'ဒဂုံမြို့သစ်(အရှ့ပိုင်း)'},
  { id: 12, code: '၁၂/ဒလန(နိုင်)', townshipname: 'ဒလမြို့နယ်'},
  { id: 12, code: '၁၂/ဒပန(နိုင်)', townshipname: '‌ဒေါပုံမြို့နယ်'},
  { id: 12, code: '၁၂/လမန(နိုင်)', townshipname: 'လှိုင်မြို့နယ်'},
  { id: 12, code: '၁၂/လသယ(နိုင်)', townshipname: 'လှိုင်သာယာမြို့နယ်'},
  { id: 12, code: '၁၂/လကန(နိုင်)', townshipname: 'လည်းကူးမြို့နယ်'},
  { id: 12, code: '၁၂/မဘန(နိုင်)', townshipname: 'မှော်ဘီမြို့နယ်'},
  { id: 12, code: '၁၂/ထတပ(နိုင်)', townshipname: 'ထန်းတပင်မြို့နယ်'},
  { id: 12, code: '၁၂/အစန(နိုင်)', townshipname: 'အင်းစိန်မြို့နယ်'},
  { id: 12, code: '၁၂/ကမရ(နိုင်)', townshipname: 'ကမာရွတ်မြို့နယ်'},
  { id: 12, code: '၁၂/ကမန(နိုင်)', townshipname: 'ကော့မှုးမြို့နယ်'},
  { id: 12, code: '၁၂/ခရန(နိုင်)', townshipname: 'ခရမ်းမြို့နယ်'},
  { id: 12, code: '၁၂/ကခက(နိုင်)', townshipname: 'ကွမ်းခြံကုန်းမြို့နယ်'},
  { id: 12, code: '၁၂/ကတတ(နိုင်)', townshipname: 'ကျောက်တံတားမြို့နယ်'},
  { id: 12, code: '၁၂/ကတန(နိုင်)', townshipname: 'ကျောက်တန်းမြို့နယ်'},
  { id: 12, code: '၁၂/ကမတ(နိုင်)', townshipname: 'ကြည့်မြင်တိုင်မြို့နယ်'},
  { id: 12, code: '၁၂/လမတ(နိုင်)', townshipname: 'လမ်းမတော်မြို့နယ်'},
  { id: 12, code: '၁၂/လသန(နိုင်)', townshipname: 'လသာမြို့နယ်'},
  { id: 12, code: '၁၂/မရက(နိုင်)', townshipname: 'မရမ်းကုန်းမြို့နယ်'},
  { id: 12, code: '၁၂/မဂဒ(နိုင်)', townshipname: 'မင်္ဂလာဒုံမြို့နယ်'},
  { id: 12, code: '၁၂/မဂတ(နိုင်)', townshipname: 'မင်္ဂလာတောင်ညွန့်'},
  { id: 12, code: '၁၂/ဥကမ(နိုင်)', townshipname: 'မြောက်ဥက္ကလာပ'},
  { id: 12, code: '၁၂/ပဘတ(နိုင်)', townshipname: 'ပန်းဘဲတန်း'},
  { id: 12, code: '၁၂/ပဇတ(နိုင်)', townshipname: 'ပုဇွန်တောင်'},
  { id: 12, code: '၁၂/စခန(နိုင်)', townshipname: 'စမ်းချောင်းမြို့နယ်'},
  { id: 12, code: '၁၂/ဆကခ(နိုင်)', townshipname: 'ဆိပ်ကြီးခနောင်တို'},
  { id: 12, code: '၁၂/ဆကန(နိုင်)', townshipname: 'ဆိပ်ကမ်း'},
  { id: 12, code: '၁၂/ရပသ(နိုင်)', townshipname: 'ရွှေပြည်သာ'},
  { id: 12, code: '၁၂/ဥကတ(နိုင်)', townshipname: 'တောင်ဥက္ကလာပ'},
  { id: 12, code: '၁၂/တကန(နိုင်)', townshipname: 'တိုက်ကြီးမြို့နယ်'},
  { id: 12, code: '၁၂/တမန(နိုင်)', townshipname: 'တာမွေမြို့နယ်'},
  { id: 12, code: '၁၂/သကတ(နိုင်)', townshipname: 'သာကေတ'},
  { id: 12, code: '၁၂/သလန(နိုင်)', townshipname: 'သန်လျင်မြို့နယ်'},
  { id: 12, code: '၁၂/သဃက(နိုင်)', townshipname: 'သင်္ဃန်းကျွန်းမြို့နယ်'},
  { id: 12, code: '၁၂/သခန(နိုင်)', townshipname: 'သုံးခွမြို့နယ်'},
  { id: 12, code: '၁၂/တတန(နိုင်)', townshipname: 'တံတားမြို့နယ်'},
  { id: 12, code: '၁၂/ရကန(နိုင်)', townshipname: 'ရန်ကင်းမြို့နယ်'},
  { id: 12, code: '၁၂/တတတ(နိုင်)', townshipname: 'တွံ့တေးမြို့နယ်'},

  { id: 12, code: '၁၂/စကတ(နိုင်)', townshipname: 'စကတ'},
  { id: 12, code: '၁၂/စမဟ(နိုင်)', townshipname: 'စမဟ'},
  

  { id: 13, code: '၁၃/ကတလ(နိုင်)', townshipname: 'ကျိုင်းတောင်းမြို့နယ်'},
  { id: 13, code: '၁၃/နခတ(နိုင်)', townshipname: 'နခတ'},
  { id: 13, code: '၁၃/အတန(နိုင်)', townshipname: 'အင်တောမြို့နယ်'},
  { id: 13, code: '၁၃/ဟမန(နိုင်)', townshipname: 'ဟိုမိန်းမြို့နယ်'},
  { id: 13, code: '၁၃/ဟပန(နိုင်)', townshipname: 'ဟိုပန်မြို့နယ်'},
  { id: 13, code: '၁၃/ဟပတ(နိုင်)', townshipname: 'ဟိုပုံးမြို့နယ်'},
  { id: 13, code: '၁၃/ကဟန(နိုင်)', townshipname: 'ကွန်ဟိန်းမြို့နယ်'},
  { id: 13, code: '၁၃/ကကန(နိုင်)', townshipname: 'ကုန်ကြမ်းမြို့နယ်'},
  { id: 13, code: '၁၃/ကခန(နိုင်)', townshipname: 'ကွတ်ခိုင်မြို့နယ်'},
  
  { id: 13, code: '၁၃/ကမန(နိုင်)', townshipname: 'ကျောက်မဲ'},
  { id: 13, code: '၁၃/ကတက(နိုင်)', townshipname: 'ကျောက်တလုံးကြီးမြို့နယ်'},

  { id: 13, code: '၁၃/ကတန(နိုင်)', townshipname: 'ကျိုင်းတုံမြို့နယ်'},
  { id: 13, code: '၁၃/ကတတ(နိုင်)', townshipname: 'ကတတ'},

  { id: 13, code: '၁၃/ကသန(နိုင်)', townshipname: 'ကျေးသီးမြို့နယ်'},
  { id: 13, code: '၁၃/ခရဟ(နိုင်)', townshipname: 'ချင်း‌ရွှေဟော်မြို့နယ်'},
  { id: 13, code: '၁၃/လကန(နိုင်)', townshipname: 'လောက်ကိုင်မြို့နယ်'},
  { id: 13, code: '၁၃/လခန(နိုင်)', townshipname: 'လင်းခေးမြို့နယ်'},
  { id: 13, code: '၁၃/လခတ(နိုင်)', townshipname: 'လဲချားမြို့နယ်'},
  { id: 13, code: '၁၃/လလန(နိုင်)', townshipname: 'လွိုင်လင်မြို့နယ်'},
  { id: 13, code: '၁၃/လရန(နိုင်)', townshipname: 'လားရှိုးမြို့နယ်'},
  { id: 13, code: '၁၃/မဘန(နိုင်)', townshipname: 'မဘိမ်းမြို့နယ်'},
  { id: 13, code: '၁၃/မဟရ(နိုင်)', townshipname: 'မန့်ဟီးရိုးမြို့နယ်'},
  { id: 13, code: '၁၃/မခန(နိုင်)', townshipname: 'မိုင်းခတ်မြို့နယ်'},
  { id: 13, code: '၁၃/မခတ(နိုင်)', townshipname: 'မိုင်းခုတ်မြို့နယ်'},
  { id: 13, code: '၁၃/မလန(နိုင်)', townshipname: 'မိုင်းလားမြို့နယ်'},

  { id: 13, code: '၁၃/မမတ(နိုင်)', townshipname: 'မမတ'},
  { id: 13, code: '၁၃/မမထ(နိုင်)', townshipname: 'မမထ'},
  { id: 13, code: '၁၃/မမန(နိုင်)', townshipname: 'မက်မန်းမြို့နယ်'},

  { id: 13, code: '၁၃/မပထ(နိုင်)', townshipname: 'မပထ'},
  { id: 13, code: '၁၃/မပတ(နိုင်)', townshipname: 'မပတ'},
  { id: 13, code: '၁၃/မပန(နိုင်)', townshipname: 'မပန'},

  { id: 13, code: '၁၃/မနန(နိုင်)', townshipname: 'မိုးနဲမြို့နယ်'},
  { id: 13, code: '၁၃/မနတ(နိုင်)', townshipname: 'မိုင်းနောင်မြို့နယ်'},

  { id: 13, code: '၁၃/မငန(နိုင်)', townshipname: 'မိုင်းငေါ့မြို့နယ်'},
  
  { id: 13, code: '၁၃/မဖတ(နိုင်)', townshipname: 'မိုင်းဖြတ်မြို့နယ်'},
  { id: 13, code: '၁၃/မဖန(နိုင်)', townshipname: 'မိုင်းဖျန်မြို့နယ်'},
  { id: 13, code: '၁၃/မစန(နိုင်)', townshipname: 'မိုင်းစံမြို့နယ်'},
  { id: 13, code: '၁၃/မဆတ(နိုင်)', townshipname: 'မူဆယ်မြို့နယ်'},
  { id: 13, code: '၁၃/မထတ(နိုင်)', townshipname: 'မော်ထိုက်မြို့နယ်'},

  { id: 13, code: '၁၃/မတန(နိုင်)', townshipname: 'မန်တွန်းမြို့နယ်'},
  { id: 13, code: '၁၃/မတတ(နိုင်)', townshipname: 'မန်တုံမြို့နယ်'},

  { id: 13, code: '၁၃/မယတ(နိုင်)', townshipname: 'မယတ'},
  { id: 13, code: '၁၃/မယထ(နိုင်)', townshipname: 'မယထ'},
  { id: 13, code: '၁၃/မယန(နိုင်)', townshipname: 'မိုင်းယန်းမြို့နယ်'},

  { id: 13, code: '၁၃/မထန(နိုင်)', townshipname: 'မုံးထမြို့နယ်'},

  { id: 13, code: '၁၃/မရတ(နိုင်)', townshipname: 'မရတ'},
  { id: 13, code: '၁၃/မရန(နိုင်)', townshipname: 'မရန'},
  
  { id: 13, code: '၁၃/နခန(နိုင်)', townshipname: 'နခန'},
  { id: 13, code: '၁၃/နမတ(နိုင်)', townshipname: 'နမတ'},

  { id: 13, code: '၁၃/နဖန(နိုင်)', townshipname: 'နဖန'},

  { id: 13, code: '၁၃/နဆန(နိုင်)', townshipname: 'နမ့်ဆန်မြို့နယ်'},
  { id: 13, code: '၁၃/နစန(နိုင်)', townshipname: 'နမ့်စန်မြို့နယ်'},

  { id: 13, code: '၁၃/နတန(နိုင်)', townshipname: 'နမ့်တစ်မြို့နယ်'},

  { id: 13, code: '၁၃/ညရန(နိုင်)', townshipname: 'ညောင်‌‌ရွှေမြို့နယ်'},

  { id: 13, code: '၁၃/ဖခန(နိုင်)', townshipname: 'ဖယ်ခုံမြို့နယ်'},

  { id: 13, code: '၁၃/ပလန(နိုင်)', townshipname: 'ပလန'},
  { id: 13, code: '၁၃/ပလတ(နိုင်)', townshipname: 'ပလတ'},

  { id: 13, code: '၁၃/ပပက(နိုင်)', townshipname: 'ပုံပါကျင်မြို့နယ်'},

  { id: 13, code: '၁၃/ပတယ(နိုင်)', townshipname: 'ပင်းတယမြို့နယ်'},
  { id: 13, code: '၁၃/ပဝန(နိုင်)', townshipname: 'ပန်ဝိုင်မြို့နယ်'},

  { id: 13, code: '၁၃/ပယန(နိုင်)', townshipname: 'ပန်ယန်းမြို့နယ်'},

  { id: 13, code: '၁၃/ဆဆန(နိုင်)', townshipname: 'ဆီဆိုင်မြို့နယ်'},
  { id: 13, code: '၁၃/တကန(နိုင်)', townshipname: 'တောင်ကြီးမြို့နယ်'},
  { id: 13, code: '၁၃/တခလ(နိုင်)', townshipname: 'တာချီလိတ်မြို့နယ်'},
  { id: 13, code: '၁၃/တလန(နိုင်)', townshipname: 'တာလေမြို့နယ်'},
  { id: 13, code: '၁၃/တမည(နိုင်)', townshipname: 'တာမိုးညဲမြို့နယ်'},
  { id: 13, code: '၁၃/တတန(နိုင်)', townshipname: 'တုံတာမြို့နယ်'},
  { id: 13, code: '၁၃/တယန(နိုင်)', townshipname: 'တန့်ယန်းမြို့နယ်'},
  { id: 13, code: '၁၃/သနန(နိုင်)', townshipname: 'သိန္နီမြို့နယ်'},
  { id: 13, code: '၁၃/သပန(နိုင်)', townshipname: 'သီပေါမြို့နယ်'},
  { id: 13, code: '၁၃/ရငန(နိုင်)', townshipname: 'ရွာငံမြို့နယ်'},
  { id: 13, code: '၁၃/ရစန(နိုင်)', townshipname: 'ရပ်စောက်မြို့နယ်'},

  { id: 13, code: '၁၃/နတရ(နိုင်)', townshipname: 'နောင်တရားမြို့နယ်'},
  { id: 13, code: '၁၃/ကလဖ(နိုင်)', townshipname: 'ကလောင်ဖာမြို့နယ်'},
  { id: 13, code: '၁၃/ခလန(နိုင်)', townshipname: 'ခိုလမ်မြို့နယ်'},


  { id: 13, code: '၁၃/ပဆန(နိုင်)', townshipname: 'ပန်ဆန်းမြို့နယ်'},
  { id: 13, code: '၁၃/ပဆတ(နိုင်)', townshipname: 'ပဆတ'},


  { id: 13, code: '၁၃/မလတ(နိုင်)', townshipname: 'မိုင်းလုံမြို့နယ်'},
  { id: 13, code: '၁၃/ပလထ(နိုင်)', townshipname: 'ပလထ'},
  
  { id: 13, code: '၁၃/မဆန(နိုင်)', townshipname: 'မိုင်းဆန်းမြို့နယ်'},
  
  { id: 13, code: '၁၃/အခန(နိုင်)', townshipname: 'အိုက်ချန်မြို့နယ်'},
  { id: 13, code: '၁၃/ဟတန(နိုင်)', townshipname: 'ဟိုတောင်းမြို့နယ်'},
  { id: 13, code: '၁၃/လထန(နိုင်)', townshipname: 'လုံထန်မြို့နယ်'},
  { id: 13, code: '၁၃/ယလန(နိုင်)', townshipname: 'ယောင်လင်းမြို့နယ်'},
  { id: 13, code: '၁၃/မမဆ(နိုင်)', townshipname: 'မန်မန်ဆိုင်မြို့နယ်'},
  { id: 13, code: '၁၃/နကန(နိုင်)', townshipname: 'နားကောင်မြို့နယ်'},

  { id: 13, code: '၁၃/မခဝ(နိုင်)', townshipname: 'မခဝ'},
  { id: 13, code: '၁၃/ကမဆ(နိုင်)', townshipname: 'ကမဆ'},


  { id: 13, code: '၁၃/နခဝ(နိုင်)', townshipname: 'နမ်းခမ်းဝူးမြို့နယ်'},
  
  { id: 13, code: '၁၃/မကထ(နိုင်)', townshipname: 'မကထ'},
  { id: 13, code: '၁၃/မကတ(နိုင်)', townshipname: 'မကတ'},
  { id: 13, code: '၁၃/မကန(နိုင်)', townshipname: 'မကန'},

  
  { id: 13, code: '၁၃/ကလထ(နိုင်)', townshipname: 'ကလထ'},
  { id: 13, code: '၁၃/ကလန(နိုင်)', townshipname: 'ကွမ်းလုံလုံ'},
  { id: 13, code: '၁၃/ကလတ(နိုင်)', townshipname: 'ကလော'},


  { id: 14, code: '၁၄/ဘကလ(နိုင်)', townshipname: 'ဘိုကလေးမြို့နယ်'},
  { id: 14, code: '၁၄/ဓနဖ(နိုင်)', townshipname: 'ဓနဖြူမြို့နယ်'},
  { id: 14, code: '၁၄/ဒဒရ(နိုင်)', townshipname: 'ဒေဒရဲမြို့နယ်'},

  { id: 14, code: '၁၄/အမန(နိုင်)', townshipname: 'အိမ်မဲမြို့နယ်'},
  { id: 14, code: '၁၄/အမတ(နိုင်)', townshipname: 'အမတ'},

  { id: 14, code: '၁၄/ဟသတ(နိုင်)', townshipname: 'ဟင်္သာတမြို့နယ်'},
  { id: 14, code: '၁၄/အဂပ(နိုင်)', townshipname: 'အင်္ဂပူမြို့နယ်'},
  { id: 14, code: '၁၄/ကကထ(နိုင်)', townshipname: 'ကန့်ကြီးထောင့်မြို့နယ်'},
  { id: 14, code: '၁၄/ကလန(နိုင်)', townshipname: 'ကျိုက်လတ်မြို့နယ်'},
  { id: 14, code: '၁၄/ကခန(နိုင်)', townshipname: 'ကြံခင်းမြို့နယ်'},
  { id: 14, code: '၁၄/ကကန(နိုင်)', townshipname: 'ကျောင်းကုန်းမြို့နယ်'},
  { id: 14, code: '၁၄/ကပန(နိုင်)', townshipname: 'ကျုံပျော်မြို့နယ်'},
  { id: 14, code: '၁၄/လပတ(နိုင်)', townshipname: 'လပ္ပတာမြို့နယ်'},
  { id: 14, code: '၁၄/လမန(နိုင်)', townshipname: 'လေးမျက်နှာမြို့နယ်'},
  { id: 14, code: '၁၄/မအပ(နိုင်)', townshipname: 'မအူပင်မြို့နယ်'},
  { id: 14, code: '၁၄/မမက(နိုင်)', townshipname: 'မော်လမြိုင်ကျွန်း'},
  { id: 14, code: '၁၄/မအန(နိုင်)', townshipname: 'မြန်အောင်မြို့နယ်'},
  { id: 14, code: '၁၄/မမန(နိုင်)', townshipname: 'မြောင်းမြမြို့နယ်'},
  { id: 14, code: '၁၄/ငပတ(နိုင်)', townshipname: 'ငပုတောမြို့နယ်'},
  { id: 14, code: '၁၄/ညတန(နိုင်)', townshipname: 'ညောင်တုန်းမြို့နယ်'},
  { id: 14, code: '၁၄/ပတန(နိုင်)', townshipname: 'ပန်းတနော်မြို့နယ်'},
  { id: 14, code: '၁၄/ပသန(နိုင်)', townshipname: 'ပုသိမ်မြို့နယ်'},
  { id: 14, code: '၁၄/ဖပန(နိုင်)', townshipname: 'ဖျာပုံမြို့နယ်'},
  { id: 14, code: '၁၄/သပန(နိုင်)', townshipname: 'သာပေါင်းမြို့နယ်'},
  { id: 14, code: '၁၄/ဝခမ(နိုင်)', townshipname: 'ဝါးခယ်မမြို့နယ်'},
  { id: 14, code: '၁၄/ရကန(နိုင်)', townshipname: 'ရေကြည်မြို့နယ်'},
  { id: 14, code: '၁၄/ဇလန(နိုင်)', townshipname: 'ဇလွန်မြို့နယ်'},
  { id: 14, code: '၁၄/ဟကက(နိုင်)', townshipname: 'ဟိုင်းကြီးကျွန်းမြို့နယ်'},
  { id: 14, code: '၁၄/ငဆန(နိုင်)', townshipname: 'ငွေဆောင်မြို့နယ်'},
  { id: 14, code: '၁၄/ငသခ(နိုင်)', townshipname: 'ငသိုင်းချောင်းမြို့နယ်'},
  { id: 14, code: '၁၄/ငရက(နိုင်)', townshipname: 'ငရုတ်ကောင်းမြို့နယ်'},
  { id: 14, code: '၁၄/ပစလ(နိုင်)', townshipname: 'ပြင်စလူမြို့နယ်'},
  { id: 14, code: '၁၄/ရသယ(နိုင်)', townshipname: '‌ရွှေသောင်ယံမြို့နယ်'},
  
  { id: 14, code: '၁၄/ပသရ(နိုင်)', townshipname: 'ပသရ'},
  { id: 14, code: '၁၄/ကကတ(နိုင်)', townshipname: 'ကကတ'},
  ]
  exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('nrc').del()
      .then(function () {
        // Inserts seed entries
        return knex('nrc').insert(nrcList)
      });
  };